add.user.bitbucket.access.extension.change.default.groups=Change {0,choice,1#account|1<accounts}
add.user.bitbucket.access.extension.info.icon.details=You must give this user access to a JIRA application before you can give this user access to Bitbucket
add.user.bitbucket.access.extension.one.account=Bitbucket ({0} account)
add.user.bitbucket.access.extension.two.accounts=Bitbucket ({0} and {1} accounts)
add.user.bitbucket.access.extension.three.accounts=Bitbucket ({0}, {1}, and {2} accounts)
add.user.bitbucket.access.extension.more.than.three.accounts=Bitbucket ({0}, {1}, {2}, and <a data-aui-trigger="" aria-controls="bitbucket-access-inline-dialog-content">{3} other</a> {3,choice,1#account|1<accounts})

application.access.bitbucket.access.extension.change.default.groups=Change {0,choice,1#account|1<accounts}
application.access.bitbucket.access.extension.one.account=These users will be invited to Bitbucket ({0} account)
application.access.bitbucket.access.extension.two.accounts=These users will be invited to Bitbucket ({0} and {1} accounts)
application.access.bitbucket.access.extension.three.accounts=These users will be invited to Bitbucket ({0}, {1}, and {2} accounts)
application.access.bitbucket.access.extension.more.than.three.accounts=These users will be invited to Bitbucket ({0}, {1}, {2}, and <a data-aui-trigger="" aria-controls="bitbucket-access-inline-dialog-content">{3} other</a> {3,choice,1#account|1<accounts})

com.atlassian.jira.plugins.dvcs.adduser.loading=Loading list of groups from Bitbucket...
com.atlassian.jira.plugins.dvcs.adduser.errorlabel=Unexpected error occurred when retrieving list of groups from Bitbucket.
com.atlassian.jira.plugins.dvcs.adduser.accounts.label=Bitbucket Accounts
com.atlassian.jira.plugins.dvcs.adduser.accounts.failed=Failed to get groups for the following accounts

com.atlassian.jira.plugins.dvcs.sync.paused=Sync Paused:
com.atlassian.jira.plugins.dvcs.github.rate.limit.reached=GitHub rate limit was exceeded. Syncing will automatically resume later.
com.atlassian.jira.plugins.dvcs.generic.error=Error during sync. See server logs.
